# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59e92724e08d0aee323327b11ba6ab871fb8fb1771c5779f54eb6fd856562fc8e78643216e632ca884abfe8b1f86a469c13d26b6d1b435abc95c912bc1cb381

test:
  secret_key_base: 00255f3835fcd7988ff9638e59c17717f4dd5a4c296d495f62dbb8f756ee997afeca99b82f51a510fba2c6e09954429e3d2c181a1ab01748c069a78b29063e47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
